export const GAME_CONFIG = Object.freeze({
  arenaRadius: 700,
  arenaWarningDistance: 85,
  maxDeltaTime: 0.05,
  bossEvery: 5,
  waveDelay: 4,
  countdownSeconds: 3,
  lockTime: 0.72,
  lockRange: 480,
  lockConeDot: 0.955,
  projectilePoolSize: 180,
  missilePoolSize: 16,
  particlePoolSize: 320,
});

export const PLAYER_CONFIG = Object.freeze({
  maxHealth: 100,
  maxShield: 100,
  radius: 2.35,
  acceleration: 82,
  reverseAcceleration: 48,
  drag: 0.48,
  normalSpeed: 105,
  boostSpeed: 168,
  boostAcceleration: 130,
  boostCapacity: 100,
  boostDrain: 29,
  boostRegen: 18,
  yawSpeed: 1.65,
  mouseSensitivity: 0.0018,
  maxPitch: Math.PI * 0.43,
  shieldRegenDelay: 3.2,
  shieldRegenRate: 18,
  fireCooldown: 0.105,
  missileCooldown: 0.8,
  missileAmmo: 6,
  rollDuration: 0.62,
  rollCooldown: 2.1,
});

export const WEAPON_CONFIG = Object.freeze({
  playerLaser: {
    speed: 430,
    damage: 18,
    radius: 0.42,
    lifetime: 2.2,
  },
  enemyLaser: {
    speed: 255,
    radius: 0.55,
    lifetime: 3.4,
  },
  missile: {
    speed: 98,
    maxSpeed: 235,
    acceleration: 145,
    turnRate: 3.2,
    damage: 92,
    splashDamage: 34,
    splashRadius: 28,
    radius: 0.85,
    lifetime: 7.5,
  },
});

export const ENEMY_TYPES = Object.freeze({
  scout: {
    label: 'Razor Scout',
    health: 52,
    speed: 116,
    acceleration: 82,
    turnRate: 2.7,
    damage: 8,
    fireCooldown: 0.88,
    preferredDistance: 115,
    attackRange: 330,
    radius: 2.35,
    evade: 1.4,
    retreatThreshold: 0.22,
    score: 150,
  },
  fighter: {
    label: 'Viper Fighter',
    health: 94,
    speed: 91,
    acceleration: 65,
    turnRate: 1.9,
    damage: 12,
    fireCooldown: 1.05,
    preferredDistance: 145,
    attackRange: 360,
    radius: 3,
    evade: 0.75,
    retreatThreshold: 0.18,
    score: 250,
  },
  heavy: {
    label: 'Marauder Heavy',
    health: 178,
    speed: 66,
    acceleration: 42,
    turnRate: 1.15,
    damage: 21,
    fireCooldown: 1.38,
    preferredDistance: 190,
    attackRange: 410,
    radius: 4.25,
    evade: 0.35,
    retreatThreshold: 0.14,
    score: 450,
  },
  boss: {
    label: 'Dreadnought Axiom',
    health: 1450,
    speed: 57,
    acceleration: 34,
    turnRate: 0.82,
    damage: 17,
    fireCooldown: 0.82,
    preferredDistance: 230,
    attackRange: 520,
    radius: 12,
    evade: 0.22,
    retreatThreshold: 0,
    score: 5000,
  },
});

export const QUALITY_PRESETS = Object.freeze({
  low: {
    pixelRatio: 1,
    stars: 900,
    nebulae: 2,
    asteroids: 12,
    debris: 38,
    particleScale: 0.55,
  },
  medium: {
    pixelRatio: 1.4,
    stars: 1900,
    nebulae: 4,
    asteroids: 20,
    debris: 85,
    particleScale: 0.8,
  },
  high: {
    pixelRatio: 1.8,
    stars: 3400,
    nebulae: 6,
    asteroids: 30,
    debris: 150,
    particleScale: 1,
  },
});

export const TEAM = Object.freeze({
  PLAYER: 'player',
  ENEMY: 'enemy',
});

export const GAME_STATE = Object.freeze({
  MENU: 'menu',
  COUNTDOWN: 'countdown',
  PLAYING: 'playing',
  PAUSED: 'paused',
  GAME_OVER: 'game-over',
});
